name: fellahi_e
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.0.8+12

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  carousel_slider: ^3.0.0
  provider: ^5.0.0
  timer_builder: ^1.3.0
  shared_preferences: ^0.5.12+4
  parse_server_sdk: ^2.0.1
  http: ^0.12.2
  fluttertoast: ^3.1.3
  flutter_sidebar: ^0.3.1
  #sqflite: ^1.2.0
  #bottom_navy_bar: ^5.3.2
  intl: ^0.17.0
  shimmer: ^1.1.1
  google_sign_in: ^4.1.0
  flutter_auth_buttons: ^0.6.0
  paging: ^0.1.0
  country_code_picker: ^1.3.7
  #pin_code_text_field: ^1.5.1
  #gradient_widgets: ^0.5.2
  gradient_app_bar: ^0.1.2
  #google_maps_flutter: ^0.5.21+8
  geolocator: ^5.2.1
  flutter_spinkit: ^4.1.1+1
  share: ^0.6.3+5
  launch_review: ^2.0.0
  flutter_google_places: ^0.2.4
  geocoder: ^0.2.1
  search_map_place: ^0.3.0
  location: ^2.4.0
#  flutter_facebook_auth : ^3.4.0
  flutter_facebook_login:
  #flutter_facebook_auth: 1.0.0
  firebase_messaging: ^7.0.0
  flutter_svg: ^0.22.0
  cached_network_image: ^2.5.1
  app_settings: ^3.0.1
  connectivity: ^0.4.8+6
  url_launcher: ^5.4.10
  flutter_html: ^1.0.0
  flutter_webview_plugin: ^0.3.11
  apple_sign_in: ^0.1.0
  scrollable_positioned_list: ^0.1.9
  readmore: ^2.0.0
  sms_autofill: ^1.3.1
  getflutter:
  crisp: ^0.1.3
  introduction_screen: ^1.0.9
  simple_tooltip: ^0.1.14
  cupertino_icons: ^0.1.2
  pinch_zoom_image_last: 0.3.2
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  js: ^0.6.2
  #google_maps: ^3.4.1
  #flutter_google_places_web: ^0.1.1
  #google_maps_flutter_web: ^0.1.0+8
  country_pickers: ^1.3.0
  pin_code_text_field: ^1.5.1
  percent_indicator: ^2.1.7+2
  image_picker: ^0.6.1+4
  dotted_border: ^1.0.7
  flutter_switch: ^0.2.0
  radio_grouped_buttons: 1.0.0+2
  firebase_remote_config: ^0.3.0+3
  get_it: ^5.0.4
  pub_semver: ^1.4.4
  package_info: ^0.4.3+2
  in_app_update: ^1.1.15
  flutter_open_whatsapp: ^0.1.2
  flutter_cache_manager: ^2.1.2
  flutter_translate: ^2.0.0
  ffi: ^1.0.0
  google_maps_flutter: ^0.5.21+8
  google_maps: ^3.4.1
  flutter_google_places_web: ^0.1.1
  google_maps_flutter_web: ^0.1.0+8
  whatsapp_unilink: ^2.0.0
  flutter_facebook_login_web: ^0.2.0
  flutter_swiper: ^1.1.6
  chewie:
  firebase_dynamic_links: ^0.6.3

  #  facebook_app_events:
#  flutter_facebook_appevents:

#  flutter_facebook_login_web: ^0.2.1

  facebook_app_events:
    path: customplugin/facebook_app_events-0.13.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  splashscreen: ^1.2.0
  flutter_launcher_icons: "^0.7.3"
  hive_generator: ^0.8.2
  build_runner: ^1.10.6

dependency_overrides:
  flutter_svg: ^0.19.2



flutter_icons:
  android: true
  ios: true
  #image_path: "assets/images/icon1.png"
  image_path_android: assets/images/icon_android.png
  image_path_ios: assets/images/icon_ios.png
#  adaptive_icon_background: assets/images/icon_background.png
#  adaptive_icon_foreground: assets/images/icon_foreground.png


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/.
    - assets/i18n/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-Regular.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
